<?php
/**
 * SMARTRESTA Operational Status Constants & System Enums
 */

// User Roles
define('ROLE_ADMIN', 'admin');
define('ROLE_MANAGER', 'manager');
define('ROLE_RECEPTION', 'reception');
define('ROLE_WAITER', 'waiter');
define('ROLE_KITCHEN', 'kitchen');

// Table Operational States
define('TABLE_STATUS_AVAILABLE', 'AVAILABLE');
define('TABLE_STATUS_OCCUPIED', 'OCCUPIED');
define('TABLE_STATUS_RESERVED', 'RESERVED');
define('TABLE_STATUS_WAITING_PAYMENT', 'WAITING_PAYMENT');
define('TABLE_STATUS_CLEANING', 'CLEANING');
define('TABLE_STATUS_OUT_OF_SERVICE', 'OUT_OF_SERVICE');

// Dining Session States
define('SESSION_STATUS_OPEN', 'OPEN');
define('SESSION_STATUS_WAITING_PAYMENT', 'WAITING_PAYMENT');
define('SESSION_STATUS_CLOSED', 'CLOSED');
define('SESSION_STATUS_CANCELLED', 'CANCELLED');

// Order Lifecycle Statuses
define('ORDER_STATUS_DRAFT', 'DRAFT');
define('ORDER_STATUS_SUBMITTED', 'SUBMITTED');
define('ORDER_STATUS_WAITING_PAYMENT', 'WAITING_PAYMENT');
define('ORDER_STATUS_CONFIRMED', 'CONFIRMED');
define('ORDER_STATUS_ROUTED', 'ROUTED');
define('ORDER_STATUS_PREPARING', 'PREPARING');
define('ORDER_STATUS_READY', 'READY');
define('ORDER_STATUS_SERVED', 'SERVED');
define('ORDER_STATUS_COMPLETED', 'COMPLETED');
define('ORDER_STATUS_CANCELLED', 'CANCELLED');
define('ORDER_STATUS_REFUNDED', 'REFUNDED');

// Order Item Statuses
define('ITEM_STATUS_PENDING', 'PENDING');
define('ITEM_STATUS_ROUTED', 'ROUTED');
define('ITEM_STATUS_PREPARING', 'PREPARING');
define('ITEM_STATUS_READY', 'READY');
define('ITEM_STATUS_SERVED', 'SERVED');
define('ITEM_STATUS_CANCELLED', 'CANCELLED');

// Payment Modes & Gateways
define('PAYMENT_MODE_PAY_FIRST', 'PAY_FIRST');
define('PAYMENT_MODE_PAY_LATER', 'PAY_LATER');
define('PAYMENT_MODE_PARTIAL', 'PARTIAL_PAYMENT');
define('PAYMENT_MODE_NO_PAYMENT', 'NO_PAYMENT_REQUIRED');

define('PAYMENT_STATUS_UNPAID', 'UNPAID');
define('PAYMENT_STATUS_PARTIAL', 'PARTIAL');
define('PAYMENT_STATUS_PAID', 'PAID');
define('PAYMENT_STATUS_REFUNDED', 'REFUNDED');

define('GATEWAY_CASH', 'Cash');
define('GATEWAY_BKASH', 'bKash');
define('GATEWAY_NAGAD', 'Nagad');
define('GATEWAY_ROCKET', 'Rocket');
define('GATEWAY_CARD', 'Card');
define('GATEWAY_OTHER', 'Other');

// Station Item Routing Modes
define('ROUTING_MODE_AUTOMATIC', 'AUTOMATIC');
define('ROUTING_MODE_MANUAL', 'MANUAL');
define('ROUTING_MODE_HYBRID', 'HYBRID');

// Commission Statuses & Rule Bases
define('COMMISSION_STATUS_PENDING', 'PENDING');
define('COMMISSION_STATUS_APPROVED', 'APPROVED');
define('COMMISSION_STATUS_PAID', 'PAID');
define('COMMISSION_STATUS_REJECTED', 'REJECTED');

define('COMMISSION_BASE_PERCENTAGE', 'PERCENTAGE');
define('COMMISSION_BASE_PER_ORDER', 'PER_ORDER');
define('COMMISSION_BASE_PER_ITEM', 'PER_ITEM');
define('COMMISSION_BASE_SALES_AMOUNT', 'SALES_AMOUNT');
